#! /bin/bash

file=~/.bashrc

if [ $1 == 'en' ]; then
    template=~/writing/template.md
    var_name=w1
    posts_path=~/writing/posts/eng/drafts/
    posts_num=$(ls $posts_path | wc -l)
    next_num=$((posts_num))
elif [ $1 == 'es' ]; then
    template=~/Documents/templates/post_template.md
    var_name=w2
    posts_path=~/writing/posts/esp/
    posts_num=$(ls $posts_path | wc -l)
    next_num=$((posts_num + 1))
else
    echo "next_post <en/es>"
    exit 1
fi

new_post="${posts_path}${next_num}.md"
new_line="export ${var_name}=${new_post}"

cp ${template} ${new_post}

sed -i "/^export ${var_name}=/c\\
${new_line}" "$file"

source $file
