#! /bin/bash

if [ $# -eq 1 ]; then
    ssh bandit$1@bandit.labs.overthewire.org -p 2220
else
    echo "ERROR: specify only the level you want to access"
    echo "Usage: 'bandid <level>'"
    exit 1
fi




